 File "/usr/local/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/typer/main.py", line 532, in wrapper
    return callback(**use_params)  # type: ignore
  File "/app/snyk_sync/cli.py", line 412, in targets
    sync()
  File "/app/snyk_sync/cli.py", line 260, in sync
    import_repos_count = import_repos.totalCount
  File "/usr/local/lib/python3.9/site-packages/github/PaginatedList.py", line 149, in totalCount
    headers, data = self.__requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.9/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.9/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.RateLimitExceededException: 403 {"message": "API rate limit exceeded for user ID 89089548.", "documentation_url": "https://urldefense.proofpoint.com/v2/url?u=https-3A__docs.github.com_rest_overview_resources-2Din-2Dthe-2Drest-2Dapi-23rate-2Dlimiting&d=DwIGaQ&c=wwDYKmuffy0jxUGHACmjfA&r=86nTYfDxlPyWYaBiGMeb8EBxTCmA-z5AKJjSH0Tg9CY&m=GHqiEXFgkP_aHTTsbUMVDrDFCqpOpFSZmUQsv8qCbZkCXnqIcZk3r413z214EsiN&s=iKDMmTqzWrVEzv01EWptrSFGq8jdU2lOlX_scnwWZUE&e= "}
